import Link from "next/link";
import {DentalDetail} from "@/components/dental-detail";
import {ArrowUpRight,CalendarPlus,ArrowRight} from "lucide-react";
import {PageShell} from "@/components/page-shell";
import {Photo} from "@/components/photo";
import {Newsletter} from "@/components/newsletter";
import {SocialLinks} from "@/components/social-links";
import {galleries} from "@/data/gallery";
export default function Home(){return <PageShell>
<section className="home-opening"><div className="shell opening-copy"><div><p className="eyebrow">Malta Association of Dental Students</p><h1>Your people.<br/>Your student years.</h1></div><div className="opening-description"><p>Representing, connecting and supporting Malta’s dental students throughout university and beyond.</p><div className="hero-actions"><Link className="button button--dark" href="/events">Explore events <ArrowUpRight size={18}/></Link></div></div></div><div className="home-photo-wrap"><Photo src="/media/committee-home-original.png" alt="The MADS 2026–2027 committee together on the University steps" className="home-group" priority/><div className="photo-caption"><div><span className="committee-year">MADS · 2026–2027</span><h2>Your committee. Here for you.</h2></div><Link className="committee-photo-link" href="/about">Meet the team <ArrowUpRight size={19}/></Link></div></div></section>
<section className="shell welcome-links" data-scroll-reveal><Link href="/contact"><span>Questions or ideas?</span><strong>Contact us <ArrowUpRight size={20}/></strong></Link><div className="welcome-social"><span>See what we’re up to</span><div className="welcome-social__row"><strong>Follow us on</strong><SocialLinks showSeparator/></div></div></section>
<section className="shell section home-events"><div data-scroll-reveal><p className="eyebrow">Get together</p><h2>What’s coming up?</h2><p>Keep space in your calendar for MADS.</p></div><div className="quiet-state" data-scroll-reveal><CalendarPlus size={28}/><h3>Keep an eye on the MADS calendar.</h3><p>We’ll add new events as they’re announced. You can also follow MADS for updates.</p><Link className="button button--outline" href="/events">View calendar</Link></div></section>
<section className="community-section"><div className="shell community-grid" data-scroll-reveal><Photo src="/media/pembroke.webp" alt={galleries[0].alt} className="community-photo"/><div className="community-copy"><DentalDetail/><p className="eyebrow">Beyond the faculty</p><h2>Small conversations.<br/>A wider community.</h2><p>From oral-health talks to volunteering, discover how MADS students get involved beyond campus.</p><Link href="/outreach" className="button button--dark">Explore our outreach <ArrowUpRight size={18}/></Link></div></div></section>
<section className="shell section"><div className="section-heading" data-scroll-reveal><div><p className="eyebrow faculty-life-label">For everyone in the faculty</p><h2>More than a timetable.</h2></div><Link href="/news" className="text-link">News & Photos <ArrowRight size={18}/></Link></div><div className="story-pair">{galleries.slice(3).map(g=><Link className="story" href={`/news/${g.slug}`} key={g.slug} data-scroll-reveal><Photo src={g.image} alt={g.alt}/><div className="story-caption"><div><p className="eyebrow">{g.category}</p><h3>{g.title}</h3></div><ArrowUpRight size={24}/></div></Link>)}</div></section>
<section className="shell section opportunity-intro" data-scroll-reveal><div><p className="eyebrow">Your next step</p><h2>Explore what’s possible.</h2></div><div><p>We’ll share exchanges, volunteering, conferences and courses once the details have been checked.</p><Link href="/opportunities" className="text-link">Browse opportunities <ArrowRight size={18}/></Link></div></section><Newsletter/></PageShell>;}
