import Link from "next/link";
import {DentalDetail} from "@/components/dental-detail";
import {ArrowUpRight,CalendarPlus,ArrowRight,MapPin} from "lucide-react";
import {PageShell} from "@/components/page-shell";
import {Photo} from "@/components/photo";
import {Newsletter} from "@/components/newsletter";
import {SocialLinks} from "@/components/social-links";
import {galleries} from "@/data/gallery";
import {publicEvents} from "@/data/site";
import {formatEventTimeRange} from "@/lib/event-format";
import {getEventLocationUrl} from "@/lib/event-location";
import { sectionMetadata, organizationSchema, websiteSchema } from "@/lib/seo";
import { StructuredData } from "@/components/structured-data";
export const metadata = sectionMetadata.home;
export default function Home(){const nextEvent=publicEvents[0];const locationUrl=getEventLocationUrl(nextEvent);return <PageShell>
<StructuredData data={[organizationSchema(), websiteSchema()]} />
<section className="home-opening"><div className="shell opening-copy"><div><p className="eyebrow">Malta Association of Dental Students</p><h1>One dental community</h1></div><div className="opening-description"><p>Representing, connecting and supporting Malta’s dental students throughout their studies.</p><div className="hero-actions"><Link className="button button--dark" href="/events">Explore events <ArrowUpRight size={18}/></Link></div></div></div><div className="home-photo-wrap"><Photo src="/media/committee-home-original.png" alt="The MADS 2026–2027 committee together on the University steps" className="home-group" priority/><div className="photo-caption"><div><span className="committee-year">MADS · 2026–2027</span><h2>Your committee. Here for you.</h2></div><Link className="committee-photo-link" href="/about">Meet the team <ArrowUpRight size={19}/></Link></div></div></section>
<section className="shell welcome-links" data-scroll-reveal><Link href="/contact"><span>Questions or ideas?</span><strong>Contact us <ArrowUpRight size={20}/></strong></Link><Link href="/#newsletter"><span>Join our newsletter</span><strong>The Molar <ArrowUpRight size={20}/></strong></Link><Link href="/opportunities"><span>Courses, exchanges & more</span><strong>Explore opportunities <ArrowUpRight size={20}/></strong></Link><div className="welcome-social"><span>See what we’re up to</span><div className="welcome-social__row"><strong>Follow us on</strong><SocialLinks showSeparator/></div></div></section>
<section className="shell section home-events"><div data-scroll-reveal><p className="eyebrow">Get together</p><h2>What’s coming up?</h2><p>Keep space in your calendar for MADS.</p></div><div className="quiet-state" data-scroll-reveal><CalendarPlus size={28}/><h3>{nextEvent.title}</h3><p>{new Date(nextEvent.date).toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long"})} · {formatEventTimeRange(nextEvent)}<br/>{locationUrl ? <a className="event-location-link home-event-location" href={locationUrl} target="_blank" rel="noopener noreferrer"><MapPin size={20} aria-hidden="true" />{nextEvent.location}</a> : <span className="home-event-location"><MapPin size={20} aria-hidden="true" />{nextEvent.location}</span>}</p><Link className="button button--outline" href={`/events/${nextEvent.slug}`} scroll={false}>Event details</Link></div></section>
<section className="community-section"><div className="shell community-grid" data-scroll-reveal><Photo src="/media/galleries/sitc/140.webp" alt="MADS volunteers speaking with visitors at Science in the City" className="community-photo"/><div className="community-copy"><DentalDetail/><p className="eyebrow">Beyond the faculty</p><h2>Small conversations.<br/>A wider community.</h2><p>From oral-health talks to volunteering, discover how MADS students get involved beyond campus.</p><Link href="/outreach" className="button button--dark">Explore our outreach <ArrowUpRight size={18}/></Link></div></div></section>
<section className="shell section"><div className="section-heading" data-scroll-reveal><div><h2>More than a timetable</h2></div><Link href="/news" className="text-link">News & Photos <ArrowRight size={18}/></Link></div><div className="story-pair">{galleries.slice(-2).map(g=><Link className="story" href={`/news/${g.slug}`} scroll={false} key={g.slug} data-scroll-reveal><Photo src={g.image} alt={g.alt}/><div className="story-caption"><div><h3>{g.title}</h3></div><ArrowUpRight size={24}/></div></Link>)}</div></section>
<section className="shell section opportunity-intro" data-scroll-reveal><div><h2>Explore what’s possible</h2></div><div><p>We’ll share exchanges, volunteering, conferences and courses so you can find something that interests you.</p><Link href="/opportunities" className="button button--dark">Explore opportunities <ArrowUpRight size={18}/></Link></div></section><Newsletter/></PageShell>;}
